#we required sudo tto install the docker CLI
language: generic
sudo: required
services:
    - docker
# command that will be executed before our tests are run or deploy our project
before_install: 
    - docker build -t mariozenuni/docker-react -f Dockerfile.dev .
script: 
    - docker run -e CI=true mariozenuni/docker-react npm run test

deploy:
    provider: elasticbeanstalk 
    region: "eu-west-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-507865947685" 
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"

    